language: node_js
node_js: stable

jobs:
  include:
    - stage: npm release
      node_js: stable
      deploy:
        skip_cleanup: true
        provider: npm
        email: "webdev@experium.ru"
        api_key: $NPM_API_KEY
        on:
          branch: npm
